#pragma config(Motor,  port1,           MobMots1,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LMots1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LMots2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMots3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LMots4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RMots1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RMots2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RMots3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RMots4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          MobMots2,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Motors 7 and 3 y cabled
/*
The numbers next to the cortex are classified as "Mot1", "Mot2", etc.
==(||)============(||)||
 ----------| 9  R  8  ||
\\\\     10|   7  6   ||
           | (Cortex) || (Rear)
////     1 |   4  5   ||
 ----------| 2  L  3  ||
==(||)============(||)||

MobMots1 = Mot1
LMots1 = Mot2 * reversed
LMots2 = Mot3
LMots3 = Mot4A and Mot4B
LMots4 = Mot5
RMots1 = Mot6
RMots2 = Mot7A and Mot7B
RMots3 = Mot8
RMots4 = Mot9
MobMots1 = Mot10

/* 5 motors each side, 2 y cabled
LMots3 is Y cabled
RMots3 is Y cabled
- polarity changed for LMots3 and RMots3
------
LMots1, LMots4, RMots1 & RMots4 are reversed.

Each Encoder count 180 Ticks/revolution
*/




/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "SkillsBotDrive.h" //drive

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/


void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	//auton();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task usercontrol()
{
  drive();
}
