#pragma config(Sensor, in1,    ClawLiftAngle,  sensorAnalog)
#pragma config(Sensor, dgtl1,  pneuBase,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  rightDEnc1,     sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  leftDEnc1,      sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftLift,       sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  rightLift,      sensorQuadEncoder)
#pragma config(Motor,  port1,           CMot,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RRevs,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LFors,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RFors,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LRevs,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          CLift,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int deadZone = 15;
bool which = false;
int width = 20;
bool opened = false;
bool up = true;


float degToInt(float deg)
{
	return ((deg * (3.14 * 4))/360);
}
void reSetDEnc()
{
	SensorValue[rightDEnc1] = 0;
	SensorValue[leftDEnc1] = 0;
}
void Right(int speed)
{
	motor[RRevs] = speed;
  motor[RFors] = speed;
}
void Left(int speed)
{
	motor[LRevs] = speed;
	motor[LFors] = speed;
}

void Right()
{
	motor[RRevs] = 127;
	motor[RFors] = 127;
}
void Left()
{
	motor[LRevs] = 127;
	motor[LFors] = 127;
}
void ReRight()
{
	motor[RRevs] = -127;
	motor[RFors] = -127;
}
void ReLeft()
{
	motor[LRevs] = -127;
	motor[LFors] = -127;
}

void Halt()
{
	motor[RRevs] = 0;
	motor[RFors] = 0;
	motor[LRevs] = 0;
	motor[LFors] = 0;
}
void turnRight(int deg)
{
	reSetDEnc();
	int s = (deg * (width/2));
  while(abs(degToInt(SensorValue[leftDEnc1])) < s)
	{
  	Left();
  }
  Halt();
}
void turnLeft(int deg)
{
	int s = deg * (width/2);
	reSetDEnc();
  while (abs(degToInt(SensorValue[rightDEnc1])) < s)
	{
  	Right();
  }
  Halt();
}
void spinLeft(int deg)
{
	int s = deg * (width/2);
	reSetDEnc();
  while (abs(degToInt(SensorValue[leftDEnc1])) < s && abs(degToInt(SensorValue[rightDEnc1])) < s)
	{
		ReRight();
  	Left();
  }
  Halt();
}
void spinRight(int deg)
{
	int s = deg * (width/2);
	reSetDEnc();
  while (abs(degToInt(SensorValue[leftDEnc1])) < s && abs(degToInt(SensorValue[rightDEnc1])) < s)
	{
		Right();
  	ReLeft();
  }
  Halt();
}

void moveInch(int powerLeft, int powerRight, int inch)
{
  reSetDEnc();
	while (abs(degToInt(SensorValue[leftDEnc1])) < inch && abs(degToInt(SensorValue[rightDEnc1])) < inch)
	{
		Right(powerLeft);
  	Left(powerRight);
  }
  Halt();
}
void moveDeg(int powerLeft, int powerRight, int deg)
{
  reSetDEnc();
	while (abs((SensorValue[leftDEnc1])) < deg && abs((SensorValue[rightDEnc1])) < deg)
	{
		Right(powerLeft);
  	Left(powerRight);
  }
  Halt();
}
void mobileUp()
{
	if (SensorValue[pneuBase] == 0) {
		SensorValue[pneuBase] = 1;
		wait10Msec(20);
  }else if (SensorValue[pneuBase] == 1) {
	  SensorValue[pneuBase] = 0;
		wait10Msec(20);
  }

}

void MoveClawTwo() //copied from drive, then modified
{

	if(!opened) //&& abs(SensorValue[CMEnc]) < 90)
	{
		motor[CMot] = 127;
		opened = true;
		wait10Msec(100);
  }
  else if(opened) //&& abs(SensorValue[CMEnc]) > 0)
  {
    motor[CMot] = -127;
    opened = false;
    wait10Msec(100);
  }
  else
  {
  	motor[CMot] = 0;
  }
  displayLCDNumber(1,3,getMotorEncoder(CMot))
}
int full = 80;
int small = 40;

void tinyLift(int power, int time)
{
    	motor[CLift] = power;
    	wait10Msec(time);

		  motor[CLift] = 0;

}

task main()
{
	//needs to have a full tank of air and fresh batteries
	reSetDEnc();
  SensorValue[pneuBase] = 1;

  moveInch(0,80,5.75);//moving //works with 5.75 and fresh battery
  wait10Msec(50);
  moveInch(127,127,29);
  wait10Msec(100);
  moveInch(60,-60,4);
  wait10Msec(50);
  moveInch(60,60,5);
  moveInch(-127,-127,11);
  wait10Msec(50);

  moveInch(127,127,2); //grabbing
  wait10Msec(50);
  moveInch(-127,127,6);
  wait10Msec(50);
  moveInch(80,80,8.5);
  wait10Msec(50);
  moveInch(80,80,2);
  wait10Msec(50);
  moveInch(0,80,3);
  wait10Msec(50);
  mobileUp();
  wait10Msec(100);
  tinyLift(127, full);
  wait10Msec(100);

  MoveClawTwo();
  wait10Msec(100);
  MoveClawTwo();
  wait10Msec(100);

  moveInch(-80,0,3);
  wait10Msec(50);
  moveInch(-127,-127,9);
  wait10Msec(50);

  moveInch(-75,75,14.5); //returning
  wait10Msec(50);
  moveInch(100,100,27.75); //scored on 28
  wait10Msec(50);
  moveInch(75,-75,6); //scored on 5
  wait10Msec(50);

  moveInch(-80,-80,6); // Scoring
  wait10Msec(100);
  moveInch(127,127,17);
  wait10Msec(90);
  moveInch(-70,-70,1);
  moveInch(-127,127,.5);
  wait10Msec(90);
  wait10Msec(50);
  moveInch(-127,-127,5);
  wait10Msec(50);
  moveInch(-75,75,8);
  wait10Msec(50);

  mobileUp();
  wait10Msec(50);
  moveInch(100,100,3);
  wait10Msec(50);
  moveInch(127,127,7);
  wait10Msec(50);

}
