#pragma config(Sensor, in1,    GyroOne,        sensorGyro)
#pragma config(Sensor, dgtl1,  LdigiEnc1,      sensorQuadEncoder)
#pragma config(Sensor, dgtl11, RdigiEnc1,      sensorQuadEncoder)
#pragma config(Motor,  port1,           Lmots,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           LMidMot,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           Rmots,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          RMidMot,          tmotorServoContinuousRotation, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int deadZone = 15;
bool which = false;

void Right(int speed)
{
	motor[Rmots] = speed;
	motor[RMidMot] = -speed;
}
void Left(int speed)
{
	motor[Lmots] = speed;
	motor[LMidMot] = -speed;
}


void Right()
{
	motor[Rmots] = 127;
	motor[RMidMot] = -127;
}
void Left()
{
	motor[Lmots] = 127;
	motor[LMidMot] = -127;
}
void ReRight()
{
	motor[Rmots] = -127;
	motor[RMidMot] = 127;
}
void ReLeft()
{
	motor[Lmots] = -127;
	motor[LMidMot] = 127;
}
void Halt()
{
	motor[Rmots] = 0;
	motor[RMidMot] = 0;
	motor[Lmots] = 0;
	motor[LMidMot] = 0;
}
float degToInt(float deg)
{
	return ((deg * (3.14 * 4))/360);
}

void goStraight(int inch)
{
	SensorValue[LdigiEnc1] = 0;
  SensorValue[RdigiEnc1] = 0;
	while (abs(degToInt(SensorValue[LdigiEnc1])) < inch && abs(degToInt(SensorValue[RdigiEnc1])) < inch)
	{
		Right();
  	Left();
  }
  Halt();
}
void TurnCheck(int target)
{
	SensorValue[GyroOne] = 0;
	int error = target - SensorValue[GyroOne];
	float kp = 0.5;
	if (error > 180)
	{
		error -= 360;
  }
  if (error < -180)
  {
    error += 360;
  }
	if (abs(error) > 1)
	{
		int speed = error * kp;
		if (speed < -100)
		{
			speed = -100;
	  }
		if (speed > 100)
		{
			speed = 100;
		}
		error = target - SensorValue[GyroOne];
		Left(error * kp);
		Right(-((error * kp));
		Halt();
	}
  while (error > 1)
	{
		error = target - SensorValue[GyroOne];
		Left(error * kp);
	}
}
void turnLeft(int deg)
{
	SensorValue[GyroOne] = 0;
  while (abs(SensorValue[GyroOne]/10) < deg)
	{
		Right();
  	ReLeft();
  }
  Halt();
  TurnCheck(deg);
}
void turnRight(int deg)
{
	SensorValue[GyroOne] = 0;
  while (abs(SensorValue[GyroOne]/10) < deg)
	{
		Left();
  	ReRight();
  }
  Halt();
}


task main()
{
	SensorValue[LdigiEnc1] = 0;
  SensorValue[RdigiEnc1] = 0;

  while(true)
  {
    goStraight(6);
    wait1Msec(2000);
    turnLeft(45);
    wait1Msec(2000);
  }
}
